spring.application.name=Food App

server.servlet.context-path=/api/v1
server.port=3002

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/foodAppDB
spring.datasource.username=
spring.datasource.password=

# Change to 'update' for production
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis configuration
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cache names
spring.cache.cache-names=Customer

# Razorpay Configuration
razorpay.key.id=rzp_test_S64gZe1ruXfmCB
razorpay.key.secret=vRcBzVaZRtHe6NUx0Q3frwjn
razorpay.currency=INR
razorpay.company.name=Food App

# Gmail SMTP Configuration for OTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=garvsharmxxa@gmail.com
spring.mail.password=jxwdiltmlaaplvra
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.from=garvsharmxxa@gmail.com

